name: Daily Export
# Purpose: Runs every day at 10 PM EST to export trading data from IBKR
# What it does:
#   1. Exports today's trades
#   2. Triggers stats update and GitHub Pages deployment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Daily at 10 PM EST

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Export IBKR Data
      uses: jefrnc/ibkr-auto-exporter@v1.3.0
      with:
        ibkr-token: ${{ secrets.IBKR_TOKEN }}
        ibkr-query-id: ${{ secrets.IBKR_QUERY_ID }}
        obfuscate-account: 'true'
    
    - name: Trigger Stats Update
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: update-stats
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' 