name: Export IBKR Trading Data

on:
  schedule:
    # Run daily at 10 PM EST (3 AM UTC)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Export IBKR data
      uses: jefrnc/ibkr-auto-exporter@v1.1.0
      with:
        ibkr-token: ${{ secrets.IBKR_TOKEN }}
        ibkr-query-id: ${{ secrets.IBKR_QUERY_ID }}
        cost-basis-min: '0'
        cost-basis-max: '50'
    
    - name: Update dashboard
      run: |
        echo "📊 Updating dashboard data..."
        python ibkr-auto-exporter/src/generate_dashboard_data.py
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: false
        force_orphan: true
        
    - name: Trigger Pages deployment
      if: github.ref == 'refs/heads/main'
      run: |
        sleep 5
        gh workflow run pages.yml || true